перенесено
Zdthns/react-burger2 pull request #1
Opened 2022-10-15 16:33 UTC by Zdthns

Проект был перезалит из за багов с синхронизацией.  В процессе "танцев с бубном" потерялись все коммиты.

2022-10-15 18:38 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодцы!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- Добавьте файл .gitignore. Прикреплю его к ревью.

- Убрать дублирование файлов root, rootReducer.

- Поправьте работу редакс стейта у модальных окон, вот нормальный ваш стейт.
   
   ![image](https://user-images.githubusercontent.com/70164458/196002720-4002ae15-35c7-47b8-8c9c-f03fbacb1629.png)

  Вот стейт модальных окон, после открытия деталей об ингредиенте.
  
  ![image](https://user-images.githubusercontent.com/70164458/196002730-ed6e978d-7338-40e9-998c-efe404a24554.png)

  Вот стейт модальных окон, после закрытия модального окна.

  ![image](https://user-images.githubusercontent.com/70164458/196002739-4b7f1665-dc04-4b75-98d4-6e9e6f88c480.png)

 Можно заметить что у вас исчезло 1 поле из исходного объекта.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**


Вот файл gitignore, переименуйте его в `.gitignore`;
[gitignore,txt](https://github.com/Zdthns/react-burger2/files/9792849/gitignore.txt)

2022-10-15 18:38 UTC, ArslanDev666 commented on src/services/reducers/modals.js
> +        };
**Надо исправить:** Здесь и далее, не забывайте возвращать текущей стейт тоже.

2022-10-18 01:28 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app. Тут я имел ввиду файлик App.test.jsx. То, что вы очистили public директорию, не критично (те файлы в основном нужны для WPA приложения).

- Отметил проблемные места в коде.

2022-10-18 01:28 UTC, ArslanDev666 commented on src/services/actions/constructor.js
> +};
**Надо исправить:** Здесь нет смысла создавать чанк, тут нет сайдэффектов, должен быть обычный action creator.

2022-10-18 01:28 UTC, ArslanDev666 commented on src/services/reducers/constructor.js
> +  constructorIngredients: [],
**Надо исправить:** Если данных нет, то следует записывать null, а не пустой объект/массив.

2022-10-18 01:28 UTC, ArslanDev666 commented on src/services/reducers/ingredient.js
> +  currentIngredient: {},
**Надо исправить:** Если данных нет, то следует записывать null, а не пустой объект/массив.

2022-10-18 01:28 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +  ingredients: [],
**Надо исправить:** Если данных нет, то следует записывать null, а не пустой объект/массив.

2022-10-18 01:28 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +  };
**Надо исправить:** Лучше разделить обработчики событий на 2, closeIngredientDetails и closeOrderDetails.

2022-10-18 10:57 UTC, Zdthns commented on src/services/reducers/constructor.js
> +  constructorIngredients: [],
Это начальный стейт данных конструктора и он пустой. Если в него записать null, то все сломается, если 0 то total вернет NAN, а конструктор отрендерит пустой итем. Возможно, я опять не правильно Вас поняла?

2022-10-18 10:57 UTC, Zdthns commented on src/services/reducers/ingredient.js
> +  currentIngredient: {},
здесь аналогично предыдущему коменту

2022-10-18 10:57 UTC, Zdthns commented on src/services/actions/constructor.js
> +};
исправлено

2022-10-18 10:58 UTC, Zdthns commented on src/services/reducers/ingredients.js
> +  ingredients: [],
здесь аналогично предыдущему коменту

2022-10-18 10:59 UTC, Zdthns commented on src/components/App/App.jsx
> +  };
исправлено

2022-10-18 11:28 UTC, Zdthns commented on src/services/reducers/constructor.js
> +  constructorIngredients: [],
хотя, уверена есть другие способы реализации стейта, которые пока мне не известны.

2022-10-18 19:05 UTC, ArslanDev666 commented on src/services/reducers/constructor.js
> +  constructorIngredients: [],
Тут дело не в самой реализации стейта. Значение у поля null - означает, что поле изначально пустое. Ну и плюс проверки намного легче с ним делать, он всегда возвращает `false`, а пустой объект или массив всегда в проверке будет true.

2022-10-19 06:54 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец! Был проведён хороших рефакторинг!**

### **Но 1 маленькое и последнее замечание, которое нужно исправить:**

- По чек листу, При нажатии на кнопку «Оформить заказ» отправляется запрос к Api. В теле запроса передается массив из \_id всех ингредиентов. У вас там где булки, передаются объекты а не `_id`, исправьте это;

![image](https://user-images.githubusercontent.com/70164458/196618049-0838f509-e74e-41be-ae9a-7479dace961e.png)

2022-10-19 06:54 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  );
**Можно лучше:** Тут лучше использовать метод find. Булка у нас всегда будет 1 и та же, поэтому не нужно делать из них массив.

2022-10-19 06:54 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  );
**Надо исправить:** неправильно реализована работа с методом find. Вы тут вытаскиваете цельный объект, а не его `_id`. Корректно будет написать вот так: 

```js 
  const orderBun = constructorIngredients.find((item) => item.type === "bun");

  // А также немного изменить логику orderData.

    const orderData = React.useMemo(() => { 
      if(!orderBun || !orderToppings.length) return [];
      
      return [orderBun.id, ...orderToppings, orderBun.id], 
    }
    [orderBun, orderToppings]
  );

```

А ещё лучше занести это в useMemo, т.к нигде больше не используется.

2022-10-19 06:54 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    .map((item) => item._id);
**Можно лучше:** это лучше занести в useMemo, т.к нигде больше не используется.

2022-10-19 09:42 UTC, Zdthns commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  );
Спасибо fix

2022-10-19 09:47 UTC, Zdthns commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const orderBun = constructorIngredients.find((item) => (item.type === 'bun') ? item._id : null);
fix

2022-10-19 17:16 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята!🔥**

- И всё же рекомендую исправить момент с пустым объектом в начальном редакс стейте (ingredientsDetail/currentIngredient). Пустой объект неоднозначно определяет есть ли данные или нет, можно подумать, что пустой объект это и есть те самые данные. Поэтому при разработке принято указывать отсутствие данных через null, а не пустыми объектами.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2022-10-19 17:16 UTC, ArslanDev666 commented on src/services/reducers/ingredient.js
> +  currentIngredient: {},
**Можно лучше:** 

И всё же рекомендую исправить момент с пустым объектом в начальном редакс стейте (ingredientsDetail/currentIngredient). Пустой объект неоднозначно определяет есть ли данные или нет, можно подумать, что пустой объект это и есть те самые данные. Поэтому при разработке принято указывать отсутствие данных через null, а не пустыми объектами.

2022-10-20 09:09 UTC, closed without merging